### ISSUE TITLE
Lifecycle callbacks not running on a model

### ISSUE THREAD

**Issue by dreamingmind** [pakacuda/cakephp-fixture-factories#22]
I have a model with a `beforeSave()` callback which is not being run.

Here is the relevant setup in my table:

```php
class LocationsTable extends Table
{

    /**
     * @var string[]
     */
    protected $digestColumns = [
        'loc_string' ,
        'zone_id' ,
    ];

    public function implementedEvents(): array
    {
        return
            [
                'Model.afterMarshal' => 'afterMarshal',
                'Model.beforeSave' => 'beforeSave'
            ];
    }

    /**
     * Set the digest value for locations
     *
     * Location stacks need to discover all the location records that refer
     * to a single location (each marking storage of a separate item).
     * A digest value derived from the zone id and location json is used.
     * a virtual field gets the json data as a string for the digest process
     *
     * @param EventInterface $event
     * @param EntityInterface $entity
     * @param ArrayObject $options
     * @return bool
     */
    public function beforeSave(EventInterface $event, EntityInterface $entity, ArrayObject $options)
    {
        $entity->digest = BusinessRules::digest($entity, $this->digestColumns);

        return true;
    }
}
```

I understand some save options and marshaling options are off by default and can be turned back on. But I don't see any mention of the callbacks...

Perhaps I'm missing something obvious?

The callback does work in the production code.

**Comment by pabloelcolombiano** [comment]
@dreamingmind Yes indeed, the Model events are all shutdown when creating the factories. This is made on purpose in order to have the injection in the DB as fast and straighforward as possible.

If you need to test the `beforeSave `of your function, I suggest that you write one or several test methods to that aim, where you then save "manually" an entity that you generated unpersisted with the factory. This way, you are really testing the `beforeSave `method, and your other unrelated tests will not be unnecessarily slowed down.

I agree that this should be added to the docs.

**Comment by dreamingmind** [comment]
Okay, thanks!

**Comment by dreamingmind** [comment]
Well, I want to toss in one more comment on this issue.

In this particular case, I do have testing for the before filter processes as a separate test. But I am trying to now make test data for a larger process that depends on the existence of a pretty large and complex set of data. The before save process is critical to having all the necessary records exist in a complete and valid state.

It may be possible for me to use the factories to make the records then write more code to back-fill the bits that the event would normally do. But this feels risky.

Would it be practical to have a switch to locally and temporarily turn on the callbacks like the save options and marshaling options?

**Comment by pabloelcolombiano** [comment]
@dreamingmind 

I understand your issue. Per default all model related listeners and behaviors (except from the TimeStamp) are skipped.

Indeed why not enable them if required. I have implemented a static method `makeWithModelListenersAndBehaviors`. If you use it instead of `make`, you should get what you required.

This also indirectly informs the developer that if he does not choose that method, but `make`, the listeners and behaviors will be skipped.

**Comment by dreamingmind** [comment]
Thanks so much! I'll give it a spin

**Comment by dreamingmind** [comment]
That's a wrap. works great
